version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    depends_on:
      - db

  proxy-service:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev
